<?php
// For Composer users (this file is generated by Composer)
require_once 'vendor/autoload.php';

// Or if you've installed the library manually, use this instead.
// require 'vendor/php-redmine-api-x.y.z/src/autoload.php';

// $client = new Redmine\Client('http://localhost', '1d1e9883fe746e732d3a42f87961211489f71e2b');
$client = new Redmine\Client('http://correlyce.atrium-sud.fr/redmine', '1d1e9883fe746e732d3a42f87961211489f71e2b');
//-- OR --
// $client = new Redmine\Client('https://correlyce.atrium-sud.fr/redmine', 'cor.sav.emls', '8rr1Z%73Zl');
// $client = new Redmine\Client('https://correlyce.atrium-sud.fr/redmine/', 'cor.sav.emls', '8rr1Z%73Zl');
// $client = new Redmine\Client('https://correlyce.atrium-sud.fr/redmine/projects', 'cor.sav.emls', '8rr1Z%73Zl');
// $client = new Redmine\Client('https://correlyce.atrium-sud.fr/redmine/projects/', 'cor.sav.emls', '8rr1Z%73Zl');
// $client = new Redmine\Client('https://correlyce.atrium-sud.fr/redmine/projects/lyceesprives', 'cor.sav.emls', '8rr1Z%73Zl');
// $client = new Redmine\Client('https://correlyce.atrium-sud.fr/redmine/projects/lyceesprives/', 'cor.sav.emls', '8rr1Z%73Zl');
// $client = new Redmine\Client('https://correlyce.atrium-sud.fr/redmine/projects/lyceesprives/issues', 'cor.sav.emls', '8rr1Z%73Zl');
// $client = new Redmine\Client('https://correlyce.atrium-sud.fr/redmine/projects/lyceesprives/issues?', 'cor.sav.emls', '8rr1Z%73Zl');
// $client = new Redmine\Client('https://correlyce.atrium-sud.fr/redmine/projects/lyceesprives/issues/1853', 'cor.sav.emls', '8rr1Z%73Zl');

$client->user->all();
$client->user->listing();

// $client->issue->create([
//     'project_id'  => 'test',
//     'subject'     => 'some subject',
//     'description' => 'a long description blablabla',
//     'assigned_to_id' => 123, // or 'assigned_to' => 'user1'
// ]);

$client->issue->all([
    'limit' => 100,
]);
$client->issue->all(['status_id' => 'Nouveau']);
// print_r($client);

// echo "<pre>";
// print_r(get_loaded_extensions());
// echo "<pre/>";

?>